#!/usr/bin/env bash
# Detect host GPU driver details and write .devcontainer/.env for docker-compose.
#
# This enables the "no-sudo" GPU passthrough path: bind-mount the host driver libs
# (libcuda, libnvidia-ml, ptxjitcompiler, nvvm) + nvidia-smi into containers, and pass
# the character devices directly. Works whether or not the nvidia container runtime
# is configured; verified on DGX Spark (GB10).
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="${repo_root}/.devcontainer/.env"

command -v nvidia-smi >/dev/null || { echo "ERROR: nvidia-smi not found — is this an NVIDIA host?" >&2; exit 1; }

# arch -> Debian multiarch triplet member
case "$(uname -m)" in
  aarch64|arm64) DEB_ARCH=aarch64 ;;
  x86_64|amd64)  DEB_ARCH=x86_64 ;;
  *) echo "ERROR: unsupported arch $(uname -m)" >&2; exit 1 ;;
esac

LIBDIR="/usr/lib/${DEB_ARCH}-linux-gnu"

# driver version from the real libcuda file the SONAME symlink points at
CUDA_TARGET="$(readlink -f "${LIBDIR}/libcuda.so.1" || true)"
[ -f "${CUDA_TARGET}" ] || { echo "ERROR: cannot resolve ${LIBDIR}/libcuda.so.1" >&2; exit 1; }
DRIVER_VERSION="${CUDA_TARGET##*.so.}"

# required driver libs present?
for lib in libnvidia-ml libnvidia-ptxjitcompiler libnvidia-nvvm; do
  ls "${LIBDIR}"/${lib}.so.* >/dev/null 2>&1 || echo "WARN: ${lib} not found in ${LIBDIR} (some libs optional)" >&2
done

# devices present?
for dev in /dev/nvidia0 /dev/nvidiactl /dev/nvidia-uvm; do
  [ -e "$dev" ] || echo "WARN: $dev missing — GPU passthrough will fail" >&2
done

cat > "${env_file}" <<EOF
# Generated by scripts/detect-host-gpu.sh on $(date -Is) — do not commit
DEB_HOST_ARCH=${DEB_ARCH}
HOST_LIBDIR=${LIBDIR}
NVIDIA_DRIVER_VERSION=${DRIVER_VERSION}
# Optional overrides:
# NGC_TAG=26.07-py3
# LLAMA_TAG=b10428
# CUDA_ARCHES=120;121
# CACHE_DIR=/absolute/path/for/model-caches
EOF

# Pre-create cache dirs as the invoking user BEFORE docker compose does (compose would
# create them root-owned, locking the host user out — verified pitfall).
mkdir -p "${repo_root}/cache"/{huggingface,torch,triton,weights}

echo "OK — wrote ${env_file}:"
grep -E '^(DEB_HOST_ARCH|HOST_LIBDIR|NVIDIA_DRIVER_VERSION)=' "${env_file}"

if docker info 2>/dev/null | grep -q '^ *Runtimes:.*nvidia'; then
  echo "NOTE: nvidia container runtime detected — 'gpus: all' also works here; the lib mounts are harmless duplicates."
fi
